/// <reference types="next" />
/// <reference types="next/image-types/global" />

// NOTE (PHASE-0.6, session 7): this file is normally auto-generated by
// `next dev`/`next build` on first run. Hand-written here since this
// session cannot run either command (no network access to install
// node_modules — see root README.md and .ai/PROJECT_STATE.md § 14/Risk
// R9). Treat as regenerable; do not hand-edit in a normal workflow.
